### ISSUE TITLE
Check if current user has rated the selected model

### ISSUE THREAD

**Issue by BechirAhmed** [codebyray/laravel-review-rateable#13]
Is it possible to check if the auth user has rated the selected model to perform updatRating instead of new rating agin?

**Comment by codebyray** [comment]
Hello,

You could do something like the following to check if the user has already rated a model:
`
// Put at the top of your controller
use Codebyray\ReviewRateable\Models\Rating;

/**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $this->data['dealerInfo'] = $this->dealer->findOrFail($id);

        // Lets check to see if the current user has already rated this dealership
        $checkRating = Rating::where('reviewrateable_id', $dealer->id)
            ->where('author_id', Auth::user()->id)
            ->first();

        if($checkDealer == null)
        {
            echo "There are no ratings for this user on this model.";
        }else{
            echo "Do something here to allow the user to update the rating."
        }

        return view('review.create', $this->data);
    }
`

Hope this helps. I plan to add an easier way to check here in the near future as it is a need for a project that is coming up.

Regards,
Ray
