### ISSUE TITLE
return averageRating with models collection

### ISSUE THREAD

**Issue by BechirAhmed** [codebyray/laravel-review-rateable#14]
It would be nice to be able to return the average ratings with models. This would allow us to show the average ratings in a models list;
for ex. $posts = Post::with('averageRating')->get();
or something like that

**Comment by codebyray** [comment]
You could write a simple query to do this now:
```mysql
SELECT reviewrateable_id, AVG(rating) AS AvgRating FROM reviews GROUP BY reviewrateable_id;
```
This particular query would give you the average overall rating for each model that has been rated. Could do the same for each of the other rating fields. 

Hope this gets you pointed in the right direction.

I like the idea and will note to add that in the next release.

Regards,
Ray

**Comment by BechirAhmed** [comment]
Okay thanks, We are waiting for the next release, good luck!
