### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sh241** [codebyray/laravel-review-rateable#16]
Hello.

How can I make a pagination?

Thank You.

**Comment by codebyray** [comment]
You could use the Rating model and run your own query for a particular list of reviews. 

```php
use use Codebyray\ReviewRateable\Models\Rating;

Rating::where('reviewrateable_id', $id)
                ->where('author_id', $author_id)
                ->paginate(10);
```

This would be your best bet at this point.
