### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by secrethash** [codebyray/laravel-review-rateable#20]
It can be made more customizable if a a new table is used for review types namely:   `customer_service_rating`, `quality_rating`, `friendly_rating`, `pricing_rating`.
A new table `review_type` could be made and used for the same. Have you thought about it?

I wanted the same type of rating system that you have created here, but its lacking customization.

**Comment by codebyray** [comment]
You're welcome to fork and create a PR if you have implemented this ability. I modified this for a project I used it on and have not gone much deeper into customizing it as of yet.

**Comment by secrethash** [comment]
Hey @codebyray , thanks for your reply. Meanwhile I forked your repo and modified a lot of things and majorly revamped the code, including the database structure. Your repository was a great help and a great start for me and thanks for that.
You can view my repo at [secrethash/r8](https://github.com/secrethash/r8)
