### ISSUE TITLE
Accessing -> reviewrateable issue after the latest update.

### ISSUE THREAD

**Issue by hadjistasi** [codebyray/laravel-review-rateable#29]
Why the update from this to the one below model Rating?! It breaks all the code and accessing -> reviewrateable always returns null with the new update. 

```php
public function reviewrateable()
{
   return $this->morphTo(); 
}
``` 

```php
public function reviewrateable()
{
   return $this->morphTo(__FUNCTION__, 'reviewable_type', 'reviewable_id'); 
}
```

**Comment by codebyray** [comment]
I will look into this. When I tested the PR is was working on my end.

**Comment by codebyray** [comment]
I am unable to find any issues, if you could provide more information about the issue you are receiving I will be more than happy to take a look.

Please include:
- PHP Version
- Laravel Verson
- Steps to duplicate

**Comment by codebyray** [comment]
Cannot duplicate and no reply. Closing issue.
