### ISSUE TITLE
Issue with last two commits. 

### ISSUE THREAD

**Issue by hadjistasi** [codebyray/laravel-review-rateable#32]
Why the update from this to the one below model Rating?! It breaks all the code and accessing -> reviewrateable in DATATABLES always returns null with the previous update.

```php
public function reviewrateable()
{
   return $this->morphTo(); 
}
public function reviewrateable()
{
   return $this->morphTo(__FUNCTION__, 'reviewable_type', 'reviewable_id'); 
}
```

Additionally, why the changes in the last update? Getting the average rating does not work anymore.

```php
$model->averageRating(null, true)->first();
```

Sorry but these last 2 commits indeed destroy this package.

@PHP 7.4
Laravel 8

**Comment by codebyray** [comment]
When getting the average for a model, the average rating is for the average of ALL ratings for that model.

To get the average rating write it like this:
```php
$model->averageRating(); // Will return the average with 4 decimals. Ex: 3.5000
```
No need to call the first() as it will error out. The only parameter you should be sending is an ``int`` for the decimal places such as:
```php
$model->averageRating(2); // Will return the float with 2 decimal places. Ex: 3.50
```
