### ISSUE TITLE
Cannot be used with the default User Model

### ISSUE THREAD

**Issue by ComputerMaverick69** [codebyray/laravel-review-rateable#35]
Trying to implement this package on the user class which extends Authenticatable throws an error of "undefined type".

```class User extends Model implements ReviewRateable``` Works
but 
```class User extends Authenticatable implements ReviewRateable``` throws `undefined type` error.

Is there a workaround? Since I don't want to directly extend model.

**Comment by codebyray** [comment]
I am unable to duplicate this issue. I have tested it on a fresh Laravel 9 install and cannot duplicate the issue. Do you have t3he proper imports setup>

```php
namespace App\Models;

use Codebyray\ReviewRateable\Contracts\ReviewRateable;
use Codebyray\ReviewRateable\Traits\ReviewRateable as ReviewRateableTrait;

class User extends Authenticatable implements ReviewRateable
{
    use ReviewRateableTrait;
```
