### ISSUE TITLE
Wrong data resualt when using this method getApprovedRatings() with two different models.

### ISSUE THREAD

**Issue by DevYSM** [codebyray/laravel-review-rateable#36]
Hello, guys, we are using your package and when using this method getApprovedRatings() with two different models we are getting a wrong result for example like this.

![image](https://user-images.githubusercontent.com/59166666/159952924-b5598669-fa8d-4c4a-836e-d5ff9ef740e1.png)

Here you must use the polymorph relationship to call the rates.
![image](https://user-images.githubusercontent.com/59166666/159952361-5f85a908-a1ca-4b91-8b59-e19c8781526b.png)

Thanks a lot.

**Comment by codebyray** [comment]
I will look into this when I have time. If you have a fix ready you can send a pull request.

**Comment by codebyray** [comment]
Have you checked that the reviewrateable_id for the App\Models\Admin and App\Models\User are not both "2".

It is entirely possible that when the Admin that is being reviewed indeed has an ID of 2 and the gym entry also has and ID of 2. As this references the actual ID for the Model that is being reviewed.
